[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cargo-husky = "1.5.0"
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
image = { version = "0.24.7", default-features = false, features = [
    "png",
    "jpeg",
] }
log = "0.4.20"
nalgebra = { version = "0.32.3", features = [
    "serde",
    "serde-serialize",
    "glam022",
] }
obj = "0.10.2"
ordered-float = "4.1.1"
simplelog = "0.12.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.27"
eframe = "0.23.0"
egui = "0.23.0"
egui_glow = "0.23.0"
bytemuck = "1.14.0"
rayon = "1.8.0"
egui_file = "0.11.1"
# mal schauen wann die version auch auf crates.io ist
bvh = { git = "https://github.com/svenstaro/bvh.git" }

#"cargo test"
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]
