[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# git hooks
cargo-husky = "1.5.0"

# error handling
anyhow = "1.0.79"

# time
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }

# image loading and saving
image = { version = "0.24.8", default-features = false, features = [
    "png",
    "jpeg",
    "tiff",
    "openexr",
] }

# logging
log = "0.4.20"
simplelog = "0.12.1"

# linear algebra
nalgebra = { version = "0.32.3", features = ["glam022"] }

# obj file loading
obj = "0.10.2"

# automatic parallelization
rayon = "1.8.0"
bytemuck = { version = "1.14.0", features = ["derive"] }

# total order for floats
ordered-float = "4.2.0"

# generic serialization / deserialization
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.30"

# GUI
eframe = { version = "0.25", features = [
    "wgpu",
    "accesskit",
    "default_fonts",
    "wayland",
    "x11",
], default-features = false }
egui = { version = "0.25", features = ["log", "color-hex"] }
egui-wgpu = { version = "0.25" }
egui_file = "0.14.1"
egui_extras = { version = "0.25", features = ["svg"] }
color-hex = "0.2.0"

# BVH
# mal schauen wann die version auch auf crates.io ist
bvh = { git = "https://github.com/svenstaro/bvh.git" }

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = [
    "user-hooks",
] }

[lints.rust]
unsafe_code = "forbid"

[profile.perftest]
inherits = "release"
debug = true
