[package]
name = "raytracing"
version = "1.0.0"
edition = "2021"
description = "Rust Raytracer."

[package.metadata.bundle]
name = "TrayRacer"
identifier = "bircni.TrayRacer"
icon = [
    "res/mac-icons/icon_16x16.png",
    "res/mac-icons/icon_32x32.png",
    "res/mac-icons/icon_128x128.png",
    "res/mac-icons/icon_256x256.png",
    "res/mac-icons/icon_16x16@2x.png",
    "res/mac-icons/icon_32x32@2x.png",
    "res/mac-icons/icon_128x128@2x.png",
]
version = "1.0.0"
resources = ["./../res/mac-icons/icon*.png"]
copyright = "© 2024 Team TrayRacer"
category = "Developer Tool"
short_description = "A Raytracer."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# error handling
anyhow = "1.0.80"

# time
chrono = { version = "0.4.34", default-features = false, features = ["clock"] }

# image loading and saving
image = { version = "0.24.9", default-features = false, features = [
    "png",
    "jpeg",
    "tiff",
    "openexr",
] }

# logging
log = "0.4.21"
simplelog = "0.12.2"

# linear algebra
nalgebra = { version = "0.32.4", features = ["glam022"] }
rand = "0.8.5"

# obj file loading
obj = "0.10.2"

# automatic parallelization
rayon = "1.9.0"
bytemuck = { version = "1.14.3", features = ["derive"] }

# total order for floats
ordered-float = "4.2.0"

# generic serialization / deserialization
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"

# GUI
eframe = { version = "0.27.1", features = [
    "wgpu",
    "accesskit",
    "default_fonts",
    "wayland",
    "x11",
], default-features = false }
egui = { version = "0.26.2", features = ["log", "color-hex"] }
egui-wgpu = { version = "0.26.2" }
egui_file = "0.16.3"
egui_extras = { version = "0.26.2", features = ["svg", "image"] }
color-hex = "0.2.0"

# BVH
# mal schauen wann die version auch auf crates.io ist
bvh = { git = "https://github.com/svenstaro/bvh.git" }
rust-i18n = "3.0.1"
sys-locale = "0.3.1"

[lints.rust]
unsafe_code = "forbid"

[profile.dev]
opt-level = 3

[profile.perftest]
inherits = "release"
debug = true
