[package]
name = "raytracing"
version = "1.0.0"
edition = "2021"
description = "Rust Raytracer."

[package.metadata.bundle]
name = "TrayRacer"
identifier = "bircni.TrayRacer"
icon = [
    "res/mac-icons/icon_16x16.png",
    "res/mac-icons/icon_32x32.png",
    "res/mac-icons/icon_128x128.png",
    "res/mac-icons/icon_256x256.png",
    "res/mac-icons/icon_16x16@2x.png",
    "res/mac-icons/icon_32x32@2x.png",
    "res/mac-icons/icon_128x128@2x.png",
]
version = "1.0.0"
resources = ["./../res/mac-icons/icon*.png"]
copyright = "© 2024 Team TrayRacer"
category = "Developer Tool"
short_description = "A Raytracer."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# error handling
anyhow = "1.0.86"

# image loading and saving
image = { version = "0.25.1", default-features = false, features = [
    "png",
    "jpeg",
    "tiff",
    "exr",
] }

# logging
log = "0.4.22"
simplelog = "0.12.2"

# linear algebra
nalgebra = { version = "0.33.0", features = ["glam022"] }
rand = "0.8.5"

# obj file loading
obj = "0.10.2"

# automatic parallelization
rayon = "1.10.0"
bytemuck = { version = "1.16.1", features = ["derive"] }

# total order for floats
ordered-float = "4.2.1"

# generic serialization / deserialization
serde = { version = "1.0.204", features = ["derive"] }
serde_yml = "0.0.10"

# GUI
eframe = { version = "0.28.1", features = [
    "wgpu",
    "accesskit",
    "default_fonts",
    "wayland",
    "x11",
], default-features = false }
egui = { version = "0.28.1", features = ["log", "color-hex"] }
egui-wgpu = { version = "0.28.1" }
egui_file = "0.18.0"
egui_extras = { version = "0.28.1", features = ["svg", "image"] }

# BVH
bvh = "0.10.0"
rust-i18n = "3.0.1"
sys-locale = "0.3.1"

[lints.rust]
unsafe_code = "forbid"

[profile.dev]
opt-level = 3

[profile.perftest]
inherits = "release"
debug = true
