title: "Raytracer"

models:

    filePath: "./res/test.obj"

  position: { x: 2.0, y: 2.0, z: 2.0 }
  rotation: { x: 2.0, y: 2.0, z: 2.0 } # in degree
  scale: 1

pointLights:

    position: { x: 2.0, y: 2.0, z: 2.0 }

  Ke: { r: 1.0, g: 1.0, b: 1.0 }

    position: { x: -1.0, y: -1.0, z: -1.0 }

  Ke: { r: 0.5, g: 0.5, b: 0.5 }

camera:
  position: { x: 0.0, y: 0.0, z: 0.0 }
  lookAt: { x: 0.0, y: 0.0, z: -1.0 }
  upVec: { x: 0.0, y: 1.0, z: 0.0 }
  fieldOfView: 60.0
  width: 1920
  height: 1080

extraArgs:
  bounces: 3
  samples: 64