title: "Raytracer"

models:
  - file_path: "./res/test.obj"
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0 # in degree
    scale: 1

point_lights:
  - position:
      x: 5.0
      y: 2.0
      z: 2.0
    ke:
      r: 15.0
      g: 15.0
      b: 15.0

  - position:
      x: -5.0
      y: 5.0
      z: -2.0
    ke:
      r: 15.0
      g: 15.0
      b: 15.0

camera:
  position:
    x: 5.0
    y: 5.0
    z: 5.0
  look_at:
    x: 0.0
    y: 0.0
    z: 0.0
  up_vec:
    x: 0.0
    y: 1.0
    z: 0.0
  field_of_view: 90.0
  width: 1920
  height: 1080

extra_args:
  max_bounces: 3
  samples: 64
  background_color:
    r: 0.0
    g: 0.0
    b: 0.0
