models:
- file_path: ./res/test.obj
  position:
    x: 0.7
    y: -0.1
    z: -0.5
  rotation:
    x: 17.761688
    y: -12.605077
    z: -6.5614495e-7
  scale: 1.0
point_lights:
- position:
    x: 5.0
    y: 2.0
    z: 2.0
  ke:
    r: 5.332843
    g: 11.98801
    b: 12.322679
- position:
    x: -5.0
    y: 5.0
    z: -2.0
  ke:
    r: 25.186932
    g: 4.616624
    b: 15.630268
camera:
  position:
    x: -2.0
    y: 1.5
    z: 5.0
  look_at:
    x: 0.0
    y: 0.0
    z: 0.0
  up_vec:
    x: 0.0
    y: 1.0
    z: 0.0
  field_of_view: 80.21409
extra_args:
  max_bounces: 3
  samples: 64
  background_color:
    r: 0.67296165
    g: 0.8369991
    b: 0.6643321
  ambient_color:
    r: 0.17478774
    g: 0.17023797
    b: 0.08521756
  skybox_texture: "res/skybox_texture_sky.jpg"