models:
- file_path: ./res/test.obj
  position:
    x: 0.7
    y: -0.1
    z: -0.5
  rotation:
    x: 1.6295541e-15
    y: -0.0
    z: 0.0
  scale: 1.0
point_lights:
- position:
    x: 0.7
    y: 4.7
    z: 2.2
  ke:
    r: 34.34196
    g: 32.57332
    b: 33.52028
camera:
  position:
    x: 2.7
    y: 1.8
    z: 7.6
  look_at:
    x: 0.5
    y: -2.0
    z: 0.0
  up_vec:
    x: 0.0
    y: 1.0
    z: 0.0
  field_of_view: 48.701416
extra_args:
  max_bounces: 3
  samples: 64
  background_color:
    r: 0.5694601
    g: 0.6880153
    b: 0.72564244
  ambient_color:
    r: 0.21685298
    g: 0.16886003
    b: 0.14555264
