#!/bin/bash

echo "Checking for cargo..."
if ! command -v cargo &>/dev/null; then
    echo "Error: cargo not found"
    exit 0
fi

echo "Executing cargo clippy"
if ! cargo clippy; then
    echo "Error: Clippy failed"
    exit 1
fi

echo "Executing cargo fmt"
if ! cargo fmt --all -- --check; then
    echo "Error: cargo fmt failed"
    exit 1
fi

echo "Everything looks good"
exit 0
