name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test

  typos:
    name: Typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main
